### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by ztNFny** [sal0max/ndx#1]
Hi,
Just stumbled upon this project. Are apks published somewhere?
If course i could build it myself, but .. :wink:

**Comment by sal0max** [comment]
Not yet, sorry. Wanted to add the last features first, before releasing production versions.
Development lost a bit of momentum, the last couple of months, but will continue!

So, for now you probably better self compile. Sorry.

**Comment by ztNFny** [comment]
Ok. Got some errors during build, in case you're not aware of them:

> Task :app:compileDebugKotlin FAILED
e: /media/daten/Github/ndx/app/src/main/kotlin/de/salomax/ndx/ui/calculator/CalculatorActivity.kt: (81, 5): 'onOptionsItemSelected' overrides nothing
e: /media/daten/Github/ndx/app/src/main/kotlin/de/salomax/ndx/ui/calibrator/CalibratorActivity.kt: (113, 5): 'onOptionsItemSelected' overrides nothing
e: /media/daten/Github/ndx/app/src/main/kotlin/de/salomax/ndx/ui/filtereditor/FilterEditorActivity.kt: (90, 5): 'onOptionsItemSelected' overrides nothing
FAILURE: Build failed with an exception.

I like the design, very clean. And the user-configurable filters are just great, that's what really annoys me about most apps (they show me lots of filters I just don't have)!
Now if there was also an aperture selection it'd be perfect ;-)

**Comment by sal0max** [comment]
Compile error fixed in 43e83be036495fc0b29d3202d907a0c9706541c1

**Comment by sal0max** [comment]
_"If a man says he'll do something he will do it. No need to remind him every six months." 😉_
So.. The app is now released, @ztNFny .

You find the apk in the release section on Github, or soon in the Play Store, once it is approved.

**Comment by sal0max** [comment]
> Now if there was also an aperture selection it'd be perfect ;-)

This is now included in v3.1.0, @ztNFny 
Feel free to give feedback, if you like to.

**Comment by ztNFny** [comment]
> > Now if there was also an aperture selection it'd be perfect ;-)
> 
> This is now included in v3.1.0, @ztNFny
> Feel free to give feedback, if you like to.

Not really what I had in mind - requires too much thinking as I have to calculate the difference in f caused by the aperture change manually.
Take a look at the first screenshot of https://play.google.com/store/apps/details?id=com.quicosoft.exposurecalculator.app

**Comment by sal0max** [comment]
> > > Now if there was also an aperture selection it'd be perfect ;-)
> > 
> > 
> > This is now included in v3.1.0, @ztNFny
> > Feel free to give feedback, if you like to.
> 
> Not really what I had in mind - requires too much thinking as I have to calculate the difference in f caused by the aperture change manually.
> Take a look at the first screenshot of https://play.google.com/store/apps/details?id=com.quicosoft.exposurecalculator.app

Thanks for the feedback!

I put a lot of thought in the implementation of the feature. And I'm aware of the "Exposure Calculator" app.
In my opinion, the solution of that app is the obvious one, but only in first thought.

When photographing in the field, I personally don't want to have to sync 3 settings (time, iso, aperture) first, and only then be able to add filters. One also has to pay attention if the dials are in sync or not, and so on. All these settings are too much to operate, when in a hustle, in my opinion. Too much space for errors.

With my solution, there's not much thinking needed:
1. You set up your camera and transfer the exposure time to the app
2. Now you add the filter(s) you desire. If that already results in the desired final exposure time: Fine! :)
3. If not: Use the compensation dial. Count the "clicks" you did. E. g. you compensated to `-1`, that's three clicks.
4. Now, all you have to do on your camera is to either reduce the iso setting by three "clicks" or increase the f-number by three "clicks".


Do you see what I mean? There's no need to calculate absolute values of the new aperture/iso. You simply dial down or up the same amount you did in the app. No matter what your base aperture/iso settings were.

Maybe the feature should just be explained better? Or do you still think my solution is more complicated than the 4 dials (iso/aperture old & new) + 2 buttons (sync iso/aperture) of the "Exposure Calculator" app?

**Comment by ztNFny** [comment]
For small adjustments the clicks sound like a simple solution.
However let's take a look at a common usecase of mine where I have the need for this app: Photographing waves, rivers, waterfalls.
1. I take a photo with the desired look, let's say f2.8, 1/400
2. I add the filter and use the app to calculate my new setting
3. take photos - so far so good
4. I want to change the look of the photo, e.g. DOF, so let's go to f11 - As i want to keep the look of the water more or less the same I'll now have to adjust ISO
yes, i can count the clicks. but what's even the point of having an app then? Maybe I'm thinking too complex here?

**Comment by sal0max** [comment]
* To answer your question _"what's even the point of having an app then"_: It is step 1 to 3.

  I agree: In your scenario, my app isn't the best support, when moving from step 3 to step 4.
My honest comment on your scenario:
In my opinion, that really doesn't make sense. You stand before a waterfall and want to take some long exposures. Cool.
However, step 4 would result in a bad, noisy photo. Given your f/2.8 shots were at base ISO100. When you close your aperture from f/2.8 to f/11 (4 full stops) and want to keep the same exposure time, you'd have to change from ISO100 to ISO1600 (4 full stops). That would result in a much noisier photo than needed.
As you already do a long exposure, it would be so much more reasonable, to alter the exposure time, maybe in combination with a lighter filter.

  In that case, you'd remove the filters, set your camera up with the new aperture setting: begin with step 1 again.

* To answer the unasked question _"what do I need the compensation dial for"_ look at following scenario:
  * I want to photograph a lake on a windy day. I want to smooth the lake and let it appear completely calm. In my experience, 20-30s is a nice exposure time to achieve that.
   * I set my aperture to f/9, as that's the sweet spot of my lens, where it's the sharpest. ISO to 100, of course.
   * Camera gives me an exposure time of 1/125.
   * I add my Lee Big Stopper (1000x), as that's my strongest filter. NDx says, that this results in 8s.
   * Now to achieve my 20-30s I turn the compensation dial to the left and at "-1 1/3" the result is 20.0s. Win!
   * Now all I have to do, is close the aperture 1 1/3 stops (4 clicks): from f/9 to f/14 (also 4 clicks).

My app is intended to be used for landscape and cityscape photography.

In my experience, this practically always means, that the photographer wants everything from front to back crisp sharp. And this means, the photographer always wants to use his lens around its sweet spot of f/9 and also wants to use base ISO100.
The compensation dial is only for those cases, where he additionally wants to achieve a certain exposure time and lacks the right filter for it. In that case, he has to compromise and alter ISO/Aperture accordingly.

I would love to hear if you could follow my line of thought and still think differently. Maybe another scenario I can relate to?
